name: Deploy to Netlify Staging
on:
    pull_request:
        types: [opened, synchronize]
        branches:
            - main
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - uses: pnpm/action-setup@v2
              with:
                  version: '8'

            - uses: actions/setup-node@v3
              with:
                  node-version: '20.x'
                  cache: pnpm

            - name: Install dependencies and build
              run: |
                  pnpm install
                  pnpm run build

            - name: Publish to Netlify
              uses: nwtgck/actions-netlify@v1.2
              id: netlify
              with:
                  publish-dir: ./build
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  github-deployment-environment: Staging
                  github-deployment-description: Deployed to Staging
                  netlify-config-path: ./netlify.toml
                  deploy-message: ${{ github.event.pull_request.title }}
                  production-deploy: false
              env:
                  NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
                  NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
              timeout-minutes: 1

            # Install playwright's binary under custom directory to cache
            - name: Set Playwright path
              run: echo "PLAYWRIGHT_BROWSERS_PATH=$HOME/.cache/playwright-bin" >> $GITHUB_ENV

            - name: Cache Playwright's binary
              id: playwright-cache
              uses: actions/cache@v3
              with:
                  # Playwright removes unused browsers automatically
                  # So does not need to add playwright version to key
                  key: ${{ runner.os }}-playwright-bin-v1
                  path: ${{ env.PLAYWRIGHT_BROWSERS_PATH }}

            - name: Install Playwright
              run: pnpm playwright install --with-deps

            - name: Run Playwright tests
              run: pnpm run test
              env:
                  PLAYWRIGHT_BASE_URL: ${{ steps.netlify.outputs.deploy-url }}

            - uses: actions/upload-artifact@v3
              if: always()
              with:
                  name: playwright-report
                  path: playwright-report/
                  retention-days: 30

            - uses: actions/upload-artifact@v3
              if: always()
              with:
                  name: playwright-snapshots
                  path: tests/*-snapshots/
                  retention-days: 30
