name: Publish on Netlify
on:
    pull_request:
        branches:
            - main
jobs:
    deploy:
        runs-on: ubuntu-latest
        environment: staging
        steps:
            - uses: actions/checkout@v3

            - uses: pnpm/action-setup@v2.2.2
              with:
                  version: '7'

            - uses: actions/setup-node@v2
              with:
                  node-version: '16.x'
                  cache: 'pnpm'

            - name: Install dependencies and build
              run: |
                  pnpm install
                  npm run build

            - name: Publish to Netlify
              uses: nwtgck/actions-netlify@v1.2
              with:
                  publish-dir: './build'
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  github-deployment-description: 'Deployed to Staging'
                  github-deployment-environment: 'staging'
                  netlify-config-path: './netlify.toml'
                  deploy-message: ${{ github.event.pull_request.title }}
              env:
                  NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
                  NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
              timeout-minutes: 1

            # - name: Install Playwright
            #   run: npx playwright install --with-deps

            # - name: Run Playwright tests
            #   run: npm run test

            #   env:
            #       PLAYWRIGHT_TEST_BASE_URL: ${{ github.event.deployment_status.target_url }}
