name: Playwright Tests
on: deployment_status
jobs:
    test:
        timeout-minutes: 60
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - uses: pnpm/action-setup@v2.2.2
              with:
                  version: '7'

            - uses: actions/setup-node@v3
              with:
                  node-version: '16.x'
                  cache: 'pnpm'

            - name: Install dependencies
              run: pnpm install

            - name: Install Playwright
              run: npx playwright install --with-deps

            - run: echo ${{ github.event.deployment_status.target_url }}
            - run: echo ${{ github.event.deployment_status.deployment_url }}
            - run: echo ${{ github.event.deployment_status.environment }}

            - name: Run Playwright tests
              run: npm run test
              env:
                  PLAYWRIGHT_BASE_URL: https://deploy-preview-9--holdengreene.netlify.app/

            - uses: actions/upload-artifact@v3
              if: always()
              with:
                  name: playwright-report
                  path: playwright-report/
                  retention-days: 30

            - uses: actions/upload-artifact@v3
              if: always()
              with:
                  name: playwright-snapshots
                  path: tests/*-snapshots/
                  retention-days: 30
