name: Playwright Tests
on: 
  deployment
jobs:
    test:
        timeout-minutes: 60
        runs-on: ubuntu-latest
        if: github.event.deployment_status.state == 'success'
        steps:
            - uses: actions/checkout@v3

            - uses: pnpm/action-setup@v2.2.2
              with:
                  version: '7'

            - uses: actions/setup-node@v2
              with:
                  node-version: '16.x'
                  cache: 'pnpm'

            - name: Install dependencies
              run: pnpm ci

            - name: Install Playwright
              run: npx playwright install --with-deps

            - name: Run Playwright tests
              run: npm run test

              env:
                  PLAYWRIGHT_TEST_BASE_URL: ${{ github.event.deployment_status.target_url }}
